name: Sync up to CodeCommit

on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git Safe Directory
        run: git config --global --add safe.directory /github/workspace

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Push to CodeCommit
        run: |
          git -c credential.helper='' -c credential.UseHttpPath=true credential approve <<EOF
          protocol=https
          host=git-codecommit.us-west-2.amazonaws.com
          username=${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
          password=${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
          EOF
          git remote add codecommit https://git-codecommit.us-west-2.amazonaws.com/v1/repos/git-commit-test-repo
          git push codecommit HEAD:main
